export const fackData = {
  drivers: [
    {
      id: "d1",
      name: "John Smith",
      phone: "01010000001",
      license: "A1001",
      vehicle: "Truck-01",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d2",
      name: "Michael Johnson",
      phone: "01010000002",
      license: "A1002",
      vehicle: "Van-01",
      shift: "evening",
      status: "busy",
      notes: "On the way to branch 3",
    },
    {
      id: "d3",
      name: "Sarah Williams",
      phone: "01010000003",
      license: "A1003",
      vehicle: "Car-01",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d4",
      name: "David Brown",
      phone: "01010000004",
      license: "A1004",
      vehicle: "Truck-02",
      shift: "night",
      status: "on_break",
      notes: "Break for 1 hour",
    },
    {
      id: "d5",
      name: "Emma Davis",
      phone: "01010000005",
      license: "A1005",
      vehicle: "Van-02",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d6",
      name: "James Miller",
      phone: "01010000006",
      license: "A1006",
      vehicle: "Truck-03",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d7",
      name: "Olivia Wilson",
      phone: "01010000007",
      license: "A1007",
      vehicle: "Car-02",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d8",
      name: "William Moore",
      phone: "01010000008",
      license: "A1008",
      vehicle: "Van-03",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d9",
      name: "Sophia Taylor",
      phone: "01010000009",
      license: "A1009",
      vehicle: "Truck-04",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d10",
      name: "Benjamin Anderson",
      phone: "01010000010",
      license: "A1010",
      vehicle: "Car-03",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d11",
      name: "Ethan Martinez",
      phone: "01010000011",
      license: "A1011",
      vehicle: "Van-04",
      shift: "evening",
      status: "available",
      notes: "",
    },
    {
      id: "d12",
      name: "Isabella Garcia",
      phone: "01010000012",
      license: "A1012",
      vehicle: "Truck-05",
      shift: "night",
      status: "on_break",
      notes: "",
    },
    {
      id: "d13",
      name: "Mason Rodriguez",
      phone: "01010000013",
      license: "A1013",
      vehicle: "Car-04",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d14",
      name: "Mia Martinez",
      phone: "01010000014",
      license: "A1014",
      vehicle: "Van-05",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d15",
      name: "Alexander Hernandez",
      phone: "01010000015",
      license: "A1015",
      vehicle: "Truck-06",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d16",
      name: "Charlotte Lopez",
      phone: "01010000016",
      license: "A1016",
      vehicle: "Car-05",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d17",
      name: "Daniel Gonzalez",
      phone: "01010000017",
      license: "A1017",
      vehicle: "Van-06",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d18",
      name: "Amelia Wilson",
      phone: "01010000018",
      license: "A1018",
      vehicle: "Truck-07",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d19",
      name: "Matthew Anderson",
      phone: "01010000019",
      license: "A1019",
      vehicle: "Car-06",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d20",
      name: "Harper Thomas",
      phone: "01010000020",
      license: "A1020",
      vehicle: "Van-07",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d21",
      name: "Joseph Jackson",
      phone: "01010000021",
      license: "A1021",
      vehicle: "Truck-08",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d22",
      name: "Evelyn White",
      phone: "01010000022",
      license: "A1022",
      vehicle: "Car-07",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d23",
      name: "Samuel Harris",
      phone: "01010000023",
      license: "A1023",
      vehicle: "Van-08",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d24",
      name: "Abigail Martin",
      phone: "01010000024",
      license: "A1024",
      vehicle: "Truck-09",
      shift: "evening",
      status: "on_break",
      notes: "",
    },
    {
      id: "d25",
      name: "David Thompson",
      phone: "01010000025",
      license: "A1025",
      vehicle: "Car-08",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d26",
      name: "Ella Garcia",
      phone: "01010000026",
      license: "A1026",
      vehicle: "Van-09",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d27",
      name: "James Martinez",
      phone: "01010000027",
      license: "A1027",
      vehicle: "Truck-10",
      shift: "morning",
      status: "busy",
      notes: "",
    },
    {
      id: "d28",
      name: "Scarlett Robinson",
      phone: "01010000028",
      license: "A1028",
      vehicle: "Car-09",
      shift: "evening",
      status: "available",
      notes: "",
    },
    {
      id: "d29",
      name: "Logan Clark",
      phone: "01010000029",
      license: "A1029",
      vehicle: "Van-10",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d30",
      name: "Victoria Lewis",
      phone: "01010000030",
      license: "A1030",
      vehicle: "Truck-11",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d31",
      name: "Andrew Lee",
      phone: "01010000031",
      license: "A1031",
      vehicle: "Car-10",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d32",
      name: "Grace Walker",
      phone: "01010000032",
      license: "A1032",
      vehicle: "Van-11",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d33",
      name: "Christopher Hall",
      phone: "01010000033",
      license: "A1033",
      vehicle: "Truck-12",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d34",
      name: "Chloe Allen",
      phone: "01010000034",
      license: "A1034",
      vehicle: "Car-11",
      shift: "evening",
      status: "available",
      notes: "",
    },
    {
      id: "d35",
      name: "Joshua Young",
      phone: "01010000035",
      license: "A1035",
      vehicle: "Van-12",
      shift: "morning",
      status: "busy",
      notes: "",
    },
    {
      id: "d36",
      name: "Zoey King",
      phone: "01010000036",
      license: "A1036",
      vehicle: "Truck-13",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d37",
      name: "Ryan Wright",
      phone: "01010000037",
      license: "A1037",
      vehicle: "Car-12",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d38",
      name: "Lily Scott",
      phone: "01010000038",
      license: "A1038",
      vehicle: "Van-13",
      shift: "evening",
      status: "on_break",
      notes: "",
    },
    {
      id: "d39",
      name: "Nathan Green",
      phone: "01010000039",
      license: "A1039",
      vehicle: "Truck-14",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d40",
      name: "Hannah Adams",
      phone: "01010000040",
      license: "A1040",
      vehicle: "Car-13",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d41",
      name: "Anthony Baker",
      phone: "01010000041",
      license: "A1041",
      vehicle: "Van-14",
      shift: "evening",
      status: "busy",
      notes: "",
    },
    {
      id: "d42",
      name: "Sofia Nelson",
      phone: "01010000042",
      license: "A1042",
      vehicle: "Truck-15",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d43",
      name: "Jack Carter",
      phone: "01010000043",
      license: "A1043",
      vehicle: "Car-14",
      shift: "night",
      status: "available",
      notes: "",
    },
    {
      id: "d44",
      name: "Aria Mitchell",
      phone: "01010000044",
      license: "A1044",
      vehicle: "Van-15",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d45",
      name: "Dylan Perez",
      phone: "01010000045",
      license: "A1045",
      vehicle: "Truck-16",
      shift: "evening",
      status: "on_break",
      notes: "",
    },
    {
      id: "d46",
      name: "Layla Roberts",
      phone: "01010000046",
      license: "A1046",
      vehicle: "Car-15",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d47",
      name: "Gabriel Turner",
      phone: "01010000047",
      license: "A1047",
      vehicle: "Van-16",
      shift: "night",
      status: "busy",
      notes: "",
    },
    {
      id: "d48",
      name: "Zoe Phillips",
      phone: "01010000048",
      license: "A1048",
      vehicle: "Truck-17",
      shift: "evening",
      status: "available",
      notes: "",
    },
    {
      id: "d49",
      name: "Henry Campbell",
      phone: "01010000049",
      license: "A1049",
      vehicle: "Car-16",
      shift: "morning",
      status: "available",
      notes: "",
    },
    {
      id: "d50",
      name: "Chloe Carter",
      phone: "01010000050",
      license: "A1050",
      vehicle: "Van-20",
      shift: "night",
      status: "available",
      notes: "",
    },
  ],
  routes: [
    {
      id: "r1",
      name: "Main Warehouse - Nasr City",
      origin: "Main Warehouse",
      destination: "Nasr City Branch",
      priority: "high",
      startTime: "2025-09-25T08:00:00Z",
      endTime: "2025-09-25T09:30:00Z",
      assignedDriverId: "d2",
      status: "in_progress",
      notes: "Urgent shipment",
    },
    {
      id: "r2",
      name: "Main Warehouse - Maadi",
      origin: "Main Warehouse",
      destination: "Maadi Branch",
      priority: "medium",
      startTime: "2025-09-25T10:00:00Z",
      endTime: "2025-09-25T11:00:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r3",
      name: "Main Warehouse - Giza",
      origin: "Main Warehouse",
      destination: "Giza Branch",
      priority: "low",
      startTime: "2025-09-25T12:00:00Z",
      endTime: "2025-09-25T13:30:00Z",
      assignedDriverId: "d5",
      status: "assigned",
      notes: "",
    },
    {
      id: "r4",
      name: "Main Warehouse - 6th October",
      origin: "Main Warehouse",
      destination: "6th October Branch",
      priority: "high",
      startTime: "2025-09-26T07:30:00Z",
      endTime: "2025-09-26T09:00:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r5",
      name: "Main Warehouse - Damietta",
      origin: "Main Warehouse",
      destination: "Damietta Branch",
      priority: "medium",
      startTime: "2025-09-26T10:00:00Z",
      endTime: "2025-09-26T13:00:00Z",
      assignedDriverId: "d1",
      status: "assigned",
      notes: "",
    },
    {
      id: "r6",
      name: "Sub Warehouse - Maadi (Small Delivery)",
      origin: "Sub Warehouse",
      destination: "Maadi Branch",
      priority: "low",
      startTime: "2025-09-27T09:00:00Z",
      endTime: "2025-09-27T09:45:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r7",
      name: "Main Warehouse - Alexandria",
      origin: "Main Warehouse",
      destination: "Alexandria Branch",
      priority: "high",
      startTime: "2025-09-27T11:00:00Z",
      endTime: "2025-09-27T15:00:00Z",
      assignedDriverId: "d10",
      status: "assigned",
      notes: "Coastal delivery",
    },
    {
      id: "r8",
      name: "Main Warehouse - Tanta",
      origin: "Main Warehouse",
      destination: "Tanta Branch",
      priority: "medium",
      startTime: "2025-09-28T08:00:00Z",
      endTime: "2025-09-28T10:00:00Z",
      assignedDriverId: "d7",
      status: "in_progress",
      notes: "",
    },
    {
      id: "r9",
      name: "Main Warehouse - Mansoura",
      origin: "Main Warehouse",
      destination: "Mansoura Branch",
      priority: "low",
      startTime: "2025-09-28T12:00:00Z",
      endTime: "2025-09-28T14:30:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r10",
      name: "Sub Warehouse - Helwan",
      origin: "Sub Warehouse",
      destination: "Helwan Branch",
      priority: "medium",
      startTime: "2025-09-29T09:00:00Z",
      endTime: "2025-09-29T11:00:00Z",
      assignedDriverId: "d3",
      status: "assigned",
      notes: "Fragile items",
    },
    {
      id: "r11",
      name: "Main Warehouse - Fayoum",
      origin: "Main Warehouse",
      destination: "Fayoum Branch",
      priority: "low",
      startTime: "2025-09-29T13:00:00Z",
      endTime: "2025-09-29T15:00:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r12",
      name: "Main Warehouse - Beni Suef",
      origin: "Main Warehouse",
      destination: "Beni Suef Branch",
      priority: "medium",
      startTime: "2025-09-30T08:30:00Z",
      endTime: "2025-09-30T11:00:00Z",
      assignedDriverId: "d12",
      status: "assigned",
      notes: "",
    },
    {
      id: "r13",
      name: "Main Warehouse - Ismailia",
      origin: "Main Warehouse",
      destination: "Ismailia Branch",
      priority: "high",
      startTime: "2025-09-30T12:00:00Z",
      endTime: "2025-09-30T14:30:00Z",
      assignedDriverId: "d8",
      status: "in_progress",
      notes: "",
    },
    {
      id: "r14",
      name: "Main Warehouse - Port Said",
      origin: "Main Warehouse",
      destination: "Port Said Branch",
      priority: "low",
      startTime: "2025-10-01T09:00:00Z",
      endTime: "2025-10-01T11:30:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r15",
      name: "Main Warehouse - Suez",
      origin: "Main Warehouse",
      destination: "Suez Branch",
      priority: "medium",
      startTime: "2025-10-01T12:30:00Z",
      endTime: "2025-10-01T14:00:00Z",
      assignedDriverId: "d20",
      status: "assigned",
      notes: "",
    },
    {
      id: "r16",
      name: "Main Warehouse - Assiut",
      origin: "Main Warehouse",
      destination: "Assiut Branch",
      priority: "high",
      startTime: "2025-10-02T07:00:00Z",
      endTime: "2025-10-02T12:00:00Z",
      assignedDriverId: "d15",
      status: "assigned",
      notes: "",
    },
    {
      id: "r18",
      name: "Main Warehouse - Sohag",
      origin: "Main Warehouse",
      destination: "Sohag Branch",
      priority: "low",
      startTime: "2025-10-02T14:00:00Z",
      endTime: "2025-10-02T18:00:00Z",
      assignedDriverId: null,
      status: "unassigned",
      notes: "",
    },
    {
      id: "r19",
      name: "Main Warehouse - Luxor",
      origin: "Main Warehouse",
      destination: "Luxor Branch",
      priority: "medium",
      startTime: "2025-10-03T08:00:00Z",
      endTime: "2025-10-03T13:00:00Z",
      assignedDriverId: "d25",
      status: "assigned",
      notes: "Touristic area delivery",
    },
    {
      id: "r20",
      name: "Main Warehouse - Aswan",
      origin: "Main Warehouse",
      destination: "Aswan Branch",
      priority: "high",
      startTime: "2025-10-03T14:00:00Z",
      endTime: "2025-10-03T20:00:00Z",
      assignedDriverId: "d30",
      status: "in_progress",
      notes: "Long distance delivery",
    },
  ],
};
